sudo: required
services:
  - docker

before_install:
  - pwd
  - docker build -t chriscasano/fib-app -f ./client/Dockerfile.dev ./client

script:
  - docker run -e -CI=true chriscasano/fib-app npm test -- --coverage

after_success:
  - docker build -t chriscasano/fib-app-client ./client
  - docker build -t chriscasano/fib-app-nginx ./client
  - docker build -t chriscasano/fib-app-server ./client
  - docker build -t chriscasano/fib-app-worker ./client

# Log into Docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Push images to Docker hub
  - docker push chriscasano/fib-app-client
  - docker push chriscasano/fib-app-nginx
  - docker push chriscasano/fib-app-server
  - docker push chriscasano/fib-app-worker
